spring:
  application:
    name: koreatestdata
  datasource:
    url: jdbc:h2:mem:testdb;
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
  sql:
    init:
      mode: always
debug: false

logging:
  level:
    org.delivery.koreatestdata: debug
    org.springframework.web.servlet: debug
---

spring:
  config:
    activate:
      on-profile: test
    datasource:
      url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;
